Custom joy node
nasa-jpl/osr-rover-code pull request #183
Opened 2024-02-25 00:27 UTC by Achllle

This PR introduces a node that allows someone to change parameters in other nodes based on Joy messages. Good starting point to making other modifications.

Depends #178

2024-02-25 00:35 UTC, Achllle commented
@abust005

2024-03-03 00:26 UTC, abust005 requested changes
Looks good, aside from that one comment

2024-03-03 00:26 UTC, abust005 commented on ROS/osr_control/osr_control/joy_extras.py
> +        if len(msg.buttons) < self.duty_button_index:
Minor thing, but is msg.buttons 0-indexed? If so, shouldn't this be <=?

2024-03-03 03:12 UTC, Achllle commented on ROS/osr_control/osr_control/joy_extras.py
> +        if len(msg.buttons) < self.duty_button_index:
you're right, good catch!

2024-03-03 03:13 UTC, Achllle commented on ROS/osr_control/osr_control/joy_extras.py
> +        if len(msg.buttons) < self.duty_button_index:
```suggestion
        if len(msg.buttons) <= self.duty_button_index:
```

2024-03-06 06:45 UTC, apollokit approved these changes
Looks fine to me, tho haven't tested. Seems like nice functionality!

Doesn't this overlap with https://github.com/nasa-jpl/osr-rover-code/pull/178 ?

2024-03-07 19:51 UTC, abust005 approved these changes

2024-03-07 19:54 UTC, Achllle commented
Yes, I'd added a dependency on #178 in the PR description. Since that's in now, I'll go ahead with merging this one as well

2024-03-07 19:56 UTC, merged